// <auto-generated />
namespace CatBDWPF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class WPFBDCAT1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WPFBDCAT1));
        
        string IMigrationMetadata.Id
        {
            get { return "202305150613198_WPFBDCAT1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
